OpenSRP/opensrp-server

- opensrp-api/src/main/java/org/opensrp/api/util/LocationTree.java
- opensrp-api/src/main/java/org/opensrp/api/util/Tree.java
- opensrp-api/src/main/java/org/opensrp/api/util/TreeNode.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/OpenmrsLocationService.java
- opensrp-web/src/main/java/org/opensrp/web/controller/UserController.java
- opensrp-web/src/test/java/org/opensrp/web/controller/TestResourceLoader.java
- opensrp-web/src/test/java/org/opensrp/web/controller/UserControllerTest.java
- releaseNotes.txt
#56 
New Features
============
- Allows to get complete location hierarchy for user during authentication
Changes
=======
- Refactoring in Tree, TreeNode and LocationTree classes for maintaining parent-child relation separately for better performance
> Complete Location tree instead of Location as a response for authentication

- opensrp-connector/src/main/java/org/opensrp/connector/FormAttributeMapper.java
- opensrp-connector/src/main/java/org/opensrp/connector/HttpUtil.java
- opensrp-connector/src/main/java/org/opensrp/connector/OpenmrsConnector.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/constants/OpenmrsConstants.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/constants/OpenmrsHouseHold.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/EncounterTest.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/HouseHoldTest.java
- opensrp-connector/src/test/resources/form/new_household_registration/form_submission5.json
- releaseNotes.txt
New Features
============
- Added javadoc for all important functions
- Added testcase for empty repeat group handling
Changes
=======
- Removed unnecessary and/or commented out code
Fixes
=====
- Fixed a bug for wrong handling of entity parent id mapping of openmrs attributes in OpenmrsConnector
> Openmrs connector javadoc

- opensrp-core/src/main/java/org/opensrp/domain/ErrorTraceForm.java
- opensrp-core/src/main/java/org/opensrp/service/ErrorTraceService.java
- opensrp-web/src/main/java/org/opensrp/web/controller/ErrorTraceController.java
> New error logging

- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/EncounterTest.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/HouseHoldTest.java
- opensrp-core/src/test/java/org/opensrp/service/MultimediaServiceTest.java
- opensrp-web/src/main/java/org/opensrp/web/controller/FormSubmissionController.java
@julkarnain please review and merge this, i have commented out some tests and some minor changes to the FormSubmissionController.
We can create another branch to address the commented out tests
> KG Put in a quick fix for the build and test failures

- assets/config/opensrp.properties
- opensrp-connector/src/main/java/org/opensrp/connector/MultipartUtility.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-core/src/main/java/org/opensrp/service/MultimediaService.java
- opensrp-core/src/test/java/org/opensrp/service/MultimediaServiceTest.java
- opensrp-core/src/test/resources/opensrp.properties
- opensrp-web/src/main/java/org/opensrp/web/controller/FormSubmissionController.java
1) I have added method to PatientService and MultipartUtility class to post multimedia files
2) I have changed the MultimediaService class and MultimediaService test class
3) I have added multimedia storing directory path in opensrp.properties file
4) I have changed mulitmedia get and post methods to send file to openmrs
> Opensrp server multimedia

- .travis.yml
- pom.xml
This pull request adds code coverage report and publishes the results to https://coveralls.io/github/OpenSRP/opensrp-server,
File changes[2]
- .travis.yml
-  pom.xml
> KG | setup code coverage

- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneActionRepository.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneClientRepository.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneEventRepository.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneSearchRepository.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/Query.java
- opensrp-web/src/main/java/org/opensrp/web/rest/EventResource.java
Signed-off-by: Ephraim Muhia <emuhia@ona.io>
> Fix: searching by baseEntityId, active status #191

- opensrp-api/src/main/java/org/opensrp/api/domain/Time.java
- opensrp-web/src/main/java/org/opensrp/web/controller/UserController.java
Add ther server's time and timezone to the login data
Fix for issue #259
Signed-off-by: Jason Rogena <jasonrogena@gmail.com>
> Server Time in Login Data

- LICENSE
- README.md
- opensrp-common/src/main/java/org/opensrp/common/AllConstants.java
- opensrp-connector/src/main/java/org/opensrp/connector/dhis2/DHIS2DatasetPush.java
- opensrp-connector/src/main/java/org/opensrp/connector/dhis2/Dhis2HttpUtils.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-connector/src/test/java/org/opensrp/connector/dhis2/DHIS2DatasetPushTest.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/TestResourceLoader.java
- opensrp-core/src/main/java/org/opensrp/domain/DataElement.java
- opensrp-core/src/main/java/org/opensrp/domain/Report.java
- opensrp-core/src/main/java/org/opensrp/domain/Stock.java
- opensrp-core/src/main/java/org/opensrp/repository/AllReports.java
- opensrp-core/src/main/java/org/opensrp/repository/AllStocks.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneReportRepository.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneStockRepository.java
- opensrp-core/src/main/java/org/opensrp/service/ReportService.java
- opensrp-core/src/main/java/org/opensrp/service/StockService.java
- opensrp-core/src/main/java/org/opensrp/service/formSubmission/FormEntityConverter.java
- opensrp-core/src/test/java/org/opensrp/service/StockServiceTest.java
- opensrp-web/src/main/java/org/opensrp/web/rest/StockResource.java
- opensrp-web/src/test/java/org/opensrp/web/rest/it/StockResourceTest.java
Waiting to test with records from the client app
> Issue260: Implement sync stock data functionality

- opensrp-web/src/main/java/org/opensrp/web/rest/ValidateResource.java
Signed-off-by: Ephraim Muhia <emuhia@ona.io>
> Validate sync rest end point

- opensrp-core/src/main/java/org/opensrp/domain/View.java
- opensrp-core/src/main/java/org/opensrp/domain/ViewConfiguration.java
- opensrp-core/src/main/java/org/opensrp/repository/ViewConfigurationRepository.java
- opensrp-core/src/main/java/org/opensrp/service/ViewConfigurationService.java
- opensrp-web/src/main/java/org/opensrp/web/rest/ViewConfigurationResource.java
**Summary of Changes**
Created a   Rest Controller , Service , Couchdb Repository and Model for Storing User configurable views as per the defined Spec
> Rest Api for fetching User Configurable Views

- assets/config/couchdb.properties
- opensrp-common/src/test/java/org/opensrp/common/util/DateUtilTest.java
- opensrp-common/src/test/java/org/opensrp/common/util/HttpUtilIntegrationTest.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsSyncerListener.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsValidateDataSync.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/EncounterService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-core/src/main/java/org/opensrp/repository/AllClients.java
- opensrp-core/src/main/java/org/opensrp/repository/AllEvents.java
- opensrp-core/src/main/java/org/opensrp/service/ClientService.java
- opensrp-web/src/main/resources/quartz.properties
Validate OMRS push data functionality
> 325 validate omrs push functionality

- opensrp-web/src/main/java/org/opensrp/web/listener/ApplicationStartupListener.java
- opensrp-web/src/main/resources/quartz.properties
Signed-off-by: keymane <emuhia@ona.io>
> Added quartz scheduler enhancements

- opensrp-connector/src/main/java/org/opensrp/connector/dhis2/DHIS2DatasetPush.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsAtomfeedListener.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsSyncerListener.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsValidateDataSync.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-core/src/main/java/org/opensrp/service/formSubmission/EventsListener.java
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
- opensrp-web/src/main/java/org/opensrp/web/listener/ApplicationStartupListener.java
- opensrp-web/src/main/resources/quartz.properties
Signed-off-by: keymane <emuhia@ona.io>
> Spring task and scheduling for application level tasks

- opensrp-core/src/main/java/org/opensrp/domain/viewconfiguration/BaseConfiguration.java
- opensrp-core/src/main/java/org/opensrp/domain/viewconfiguration/RegisterConfiguration.java
User configurable Presumptive Patients Register Configuration
> User configurable Presumptive Patients Register Configuration

- opensrp-connector/src/test/java/org/opensrp/connector/dhis2/DHIS2DatasetPushTest.java
- opensrp-core/src/main/java/org/opensrp/repository/AllClients.java
- opensrp-core/src/main/java/org/opensrp/repository/AllEvents.java
- opensrp-core/src/main/java/org/opensrp/repository/AllReports.java
- opensrp-core/src/main/java/org/opensrp/service/formSubmission/EventsListener.java
- opensrp-core/src/test/java/org/opensrp/service/formSubmission/EventListenerTest.java
Signed-off-by: Ephraim Muhia <keyman@Ephraims-MacBook-Pro.local>
> Added limits to fetching docs by server version

- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsSyncerListener.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsValidateDataSync.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
Signed-off-by: Ephraim Muhia <keyman@Ephraims-MacBook-Pro.local>
> Replace strings/locations not accepted in OMRS

- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/constants/OpenmrsConstants.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsValidateDataSync.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/EncounterService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/HouseholdService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/OpenmrsSchedulerService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/OpenmrsUserService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/EncounterTest.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/OpenmrsSchedulerServiceTest.java
- opensrp-connector/src/test/java/org/opensrp/connector/openmrs/service/PatientTest.java
- opensrp-core/src/main/java/org/opensrp/repository/AllEvents.java
- opensrp-core/src/main/java/org/opensrp/service/EventService.java
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
- opensrp-web/src/main/java/org/opensrp/web/controller/FormSubmissionController.java
Signed-off-by: Ephraim Muhia <keyman@Ephraims-MacBook-Pro.local>
> Cleanup sync to openmrs

- opensrp-core/src/main/java/org/opensrp/domain/Address.java
- opensrp-web/src/main/java/org/opensrp/web/rest/EventResource.java
- opensrp-web/src/test/java/org/opensrp/web/rest/it/StockResourceTest.java
Signed-off-by: Ephraim Muhia <emuhia@ona.io>
> Fix for fetching missing clients after sync search

- opensrp-core/src/main/java/org/opensrp/service/formSubmission/EventsListener.java
PR for fixing [Issue381](https://github.com/OpenSRP/opensrp-server/issues/379) on path branch
> PATH: Fix issue of duplicate server versions

- opensrp-core/src/main/java/org/opensrp/service/formSubmission/EventsListener.java
PR for fixing [Issue381](https://github.com/OpenSRP/opensrp-server/issues/379) on master branch
> Master: Fix issue of duplicate server versions

- opensrp-core/src/main/java/org/opensrp/service/formSubmission/EventsListener.java
PR for fixing [Issue381](https://github.com/OpenSRP/opensrp-server/issues/379) on tb-reach branch
> TBR: Fix issue of duplicate event server versions

- opensrp-common/src/main/java/org/opensrp/common/AllConstants.java
- opensrp-core/src/main/java/org/opensrp/domain/Order.java
- opensrp-core/src/main/java/org/opensrp/exception/LuceneIOException.java
- opensrp-core/src/main/java/org/opensrp/repository/AllOrders.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneOrderRepository.java
- opensrp-core/src/main/java/org/opensrp/service/OrderService.java
- opensrp-web/src/main/java/org/opensrp/web/rest/OrderResource.java
1. The client should send a GET request to the /sync end-point on the OpenSRP server.
2. The client receive either a success 200 or failure 500 response.
3. A sample success JSON payload is:
```
{
"orders": [
{
"clientIdentifier": 44,
"locationId": "o90sdkljfds0change2",
"providerId": "iosdio9w9",
"dateCreatedByClient": 98989324,
"dateCreated": "2018-02-27T07:20:01.077Z",
"voided": false,
"serverVersion": 1519716001075,
"type": "Order",
"id": "a030f309ca79ba78f05cc513ae07d5ed",
"revision": "1-a0a0c0b4c8a9554690d6f264f04df494"
},
}
```
See more at: #388
> orders sync endpoint

- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/OpenmrsUserService.java
- opensrp-web/src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
Signed-off-by: Ephraim Muhia <emuhia@ona.io>
> Added custom error messages

- opensrp-core/src/main/java/org/opensrp/repository/AllClients.java
Added functionality to get openMRS null uuids for clients when validating
> Added functionality to get openmrs null uuids

- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/schedule/OpenmrsSyncerListener.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/EncounterService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/OpenmrsService.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-core/src/main/java/org/opensrp/service/ClientService.java
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
No ready to Merge as other related issues are not fixed 
Issues fixed
> Zeir updates to omrs

- opensrp-core/src/main/java/org/opensrp/domain/Order.java
- opensrp-core/src/main/java/org/opensrp/domain/Shipment.java
- opensrp-web/src/main/java/org/opensrp/web/rest/OrderResource.java
- opensrp-web/src/main/java/org/opensrp/web/rest/ShipmentResource.java
See more at #418 
Add /getOrders endpoint
> Add stock on hand and openlmis order code

- assets/config/opensrp.properties
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
- opensrp-core/src/main/resources/persistence_postgres.xml
- opensrp-web/pom.xml
- opensrp-web/src/main/java/org/opensrp/web/controller/MultimediaController.java
- opensrp-web/src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- opensrp-web/src/main/webapp/WEB-INF/web.xml
- pom.xml
PR for 
-  [Issue 448](https://github.com/OpenSRP/opensrp-server/issues/448)
- [Issue 452](https://github.com/OpenSRP/opensrp-server/issues/452)
> UG HPV Cache Authentication

- assets/config/opensrp.properties
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
- opensrp-core/src/main/resources/persistence_postgres.xml
- opensrp-web/pom.xml
- opensrp-web/src/main/java/org/opensrp/web/controller/MultimediaController.java
- opensrp-web/src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- opensrp-web/src/main/webapp/WEB-INF/web.xml
- pom.xml
TB Reach PR for 
-  [Issue 448](https://github.com/OpenSRP/opensrp-server/issues/448)
- [Issue 452](https://github.com/OpenSRP/opensrp-server/issues/452)
> TB Reach Cache authentication

- assets/config/opensrp.properties
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
- opensrp-core/src/main/resources/persistence_postgres.xml
- opensrp-web/pom.xml
- opensrp-web/src/main/java/org/opensrp/web/controller/MultimediaController.java
- opensrp-web/src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- opensrp-web/src/main/webapp/WEB-INF/web.xml
- pom.xml
PR for 
-  [Issue 448](https://github.com/OpenSRP/opensrp-server/issues/448)
- [Issue 452](https://github.com/OpenSRP/opensrp-server/issues/452)
> Cache authentication

- assets/tbreach_default_view_configs/README.txt
- assets/tbreach_default_view_configs/setup_view_configs.sh
PR for [Issue 458](https://github.com/OpenSRP/opensrp-server/issues/458)
> View configuration setup script add postgres support

- assets/tbreach_default_view_configs/README.txt
- assets/tbreach_default_view_configs/setup_view_configs.sh
PR for [Issue 458](https://github.com/OpenSRP/opensrp-server/issues/458)
> Uganda HPV View configuration setup script add postgres support

- opensrp-core/src/main/java/org/opensrp/domain/BaseDataObject.java
- opensrp-core/src/main/java/org/opensrp/domain/Event.java
> Add client application and database version identifiers to the EC model UGANDA HPV

- opensrp-common/src/main/java/org/opensrp/common/AllConstants.java
- opensrp-connector/src/main/java/org/opensrp/connector/openmrs/service/PatientService.java
- opensrp-core/src/main/java/org/opensrp/domain/RapidProContact.java
- opensrp-core/src/main/java/org/opensrp/repository/lucene/LuceneEventRepository.java
- opensrp-web/src/main/java/org/opensrp/web/rest/rapid/RapidProResource.java
Adding new endpoint to query and update new contacts in opensrp database
> mVacc Integration 

- assets/config/opensrp.properties
- opensrp-core/src/main/resources/applicationContext-opensrp.xml
- opensrp-core/src/main/resources/persistence_postgres.xml
- opensrp-web/pom.xml
- opensrp-web/src/main/java/org/opensrp/web/controller/MultimediaController.java
- opensrp-web/src/main/java/org/opensrp/web/security/DrishtiAuthenticationProvider.java
- opensrp-web/src/main/webapp/WEB-INF/web.xml
- pom.xml
Path PR for [Issue448](https://github.com/OpenSRP/opensrp-server/issues/448)
> Issue448 path cache authentication
